# 1) Data Exploration

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


## 1.1 Loading the data


In [2]:
data = load_breast_cancer()
print(data.DESCR)


.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

## 1.2 Visualizing the data

In [3]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df.sample(15)


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
266       10.600         18.95           69.28      346.4          0.09688   
539        7.691         25.44           48.34      170.4          0.08668   
439       14.020         15.66           89.59      606.5          0.07966   
256       19.550         28.77          133.60     1207.0          0.09260   
297       11.760         18.14           75.00      431.1          0.09968   
415       11.890         21.17           76.39      433.8          0.09773   
546       10.320         16.35           65.31      324.9          0.09434   
201       17.540         19.32          115.10      951.6          0.08968   
134       18.450         21.91          120.20     1075.0          0.09430   
453       14.530         13.98           93.86      644.2          0.10990   
124       13.370         16.39           86.10      553.5          0.07115   
461       27.420         26.27          186.90     2501.0          0.10840   
306       13.200         15.82           84.07      537.3          0.08511   
183       11.410         14.92           73.53      402.0          0.09059   
169       14.970         16.95           96.22      685.9          0.09855   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
266           0.11470        0.063870             0.026420         0.1922   
539           0.11990        0.092520             0.013640         0.2037   
439           0.05581        0.020870             0.026520         0.1589   
256           0.20630        0.178400             0.114400         0.1893   
297           0.05914        0.026850             0.035150         0.1619   
415           0.08120        0.025550             0.021790         0.2019   
546           0.04994        0.010120             0.005495         0.1885   
201           0.11980        0.103600             0.074880         0.1506   
134           0.09709        0.115300             0.068470         0.1692   
453           0.09242        0.068950             0.064950         0.1650   
124           0.07325        0.080920             0.028000         0.1422   
461           0.19880        0.363500             0.168900         0.2061   
306           0.05251        0.001461             0.003261         0.1632   
183           0.08155        0.061810             0.023610         0.1167   
169           0.07885        0.026020             0.037810         0.1780   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
266                 0.06491  ...          22.94            78.28       424.8   
539                 0.07751  ...          31.89            54.49       223.6   
439                 0.05586  ...          19.31            96.53       688.9   
256                 0.06232  ...          36.27           178.60      1926.0   
297                 0.06287  ...          23.39            85.10       553.6   
415                 0.06290  ...          27.21            85.09       522.9   
546                 0.06201  ...          21.77            71.12       384.9   
201                 0.05491  ...          25.84           139.50      1239.0   
134                 0.05727  ...          31.39           145.60      1590.0   
453                 0.06121  ...          16.93           103.10       749.9   
124                 0.05823  ...          22.75            91.99       632.1   
461                 0.05623  ...          31.37           251.20      4254.0   
306                 0.05894  ...          20.45            92.00       636.9   
183                 0.06217  ...          17.70            79.12       467.2   
169                 0.05650  ...          23.00           104.60       793.7   

     worst smoothness  worst compactness  worst concavity  \
266            0.1213            0.25150          0.19160   
539            0.1596            0.30640          0.33930   
439            0.1034            0.10170          0.06260  

In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

On peut voir que toutes les données sont numériques et qu'il ne manque pas de valeurs
Les données sont déjà nettoyées, on peut s'attaquer au modèle

## 2) Model(s)

### 2.1 Etablissons nos features ainsi que notre target

In [5]:
X, y = data.data, data.target


### 2.2 Divisons nos données en deux : entrainement et test

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


## 2.3  Essayons plusieurs modèles de classification et vérifions leur performance

### 2.3.1 Logistic Regression, ce modèle est assez simple et peut servir de baseline

In [7]:
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Logistic Regression:")
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)
print('Classification Report:')
print(report)


Logistic Regression:
Accuracy: 0.96
Confusion Matrix:
[[39  4]
 [ 1 70]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



### 2.4 K-Nearest Neighbors

In [8]:
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("K-Nearest Neighbors:")
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)
print('Classification Report:')
print(report)


K-Nearest Neighbors:
Accuracy: 0.96
Confusion Matrix:
[[39  4]
 [ 1 70]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



### 2.5 Random Forest

In [9]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Random Forest:")
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion)
print('Classification Report:')
print(report)


Random Forest:
Accuracy: 0.96
Confusion Matrix:
[[40  3]
 [ 1 70]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



### D'après ces résultats, je décide de choisir le modèle Random Forest pour notre tâche de classification